### ISSUE TITLE
Transformer not working in js

### ISSUE THREAD

**Issue by djaffer** [huggingface/transformers.js#1021]
### System Info

```
@xenova/transformers": "^2.17.2
@huggingface/transformers:"^3.0.2"
```

### Environment/Platform

- [ ] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

Unexpected token '<', "<!doctype "... is not valid JSON
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at getModelJSON (http://localhost:3025/static/js/vendors-node_modules_xenova_transformers_src_models_js-node_modules_xenova_transformers_src_t-98979f.chunk.js:35589:15)
    at async Promise.all (index 0)
    at async loadTokenizer (http://localhost:3025/static/js/vendors-node_modules_xenova_transformers_src_models_js-node_modules_xenova_transformers_src_t-98979f.chunk.js:28435:16)
    at async AutoTokenizer.from_pretrained (http://localhost:3025/static/js/vendors-node_modules_xenova_transformers_src_models_js-node_modules_xenova_transformers_src_t-98979f.chunk.js:32349:46)
    at async Promise.all (index 0)
    at async loadItems (http://localhost:3025/static/js/vendors-node_modules_xenova_transformers_src_models_js-node_modules_xenova_transformers_src_t-98979f.chunk.js:26304:3)
    at async pipeline (http://localhost:3025/static/js/vendors-node_modules_xenova_transformers_src_models_js-node_modules_xenova_transformers_src_t-98979f.chunk.js:26249:19)
    at async testModel (http://localhost:3025/static/js/bundle.js:39226:18)

### Reproduction

Tried with `@xenova/transformers` too and then tried with `@huggingface/transformers`.

```
const pipe = await pipeline('sentiment-analysis');
const out = await pipe('I love transformers!');
console.log(out);

const extractor = await pipeline('feature-extraction', 'Xenova/bge-base-en-v1.5');
const texts = ['Hello world.', 'Example sentence.'];
const embeddings = await extractor(texts, { pooling: 'mean', normalize: true });
console.log(embeddings);
```

**Comment by xenova** [comment]
Hi there 👋 This should have been fixed in `@huggingface/transformers`. Can you provide the error log for that (the ones shown above are for `@xenova/transformers`)?

Note: You must uninstall `@xenova/transformers` and replace all imports of `@xenova/transformers` with `@huggingface/transformers`

**Comment by djaffer** [comment]
I will try again. The model wasn't working with  @huggingface/transformers.

**Comment by Rayid-Ashraf** [comment]
Hey, I ran into the same issue. Did anyone found the solution for it ?
