### ISSUE TITLE
Janus-1.3B-ONNX - Can't create a session. Failed to allocate a buffer

### ISSUE THREAD

**Issue by finalstack** [huggingface/transformers.js#1056]
### System Info

Transfomer.js version: "@huggingface/transformers": "^3.1.0"

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I was trying the code provided in the `onnx-community/Janus-1.3B-ONNX` repository, but I encountered the following error:

```
ort.webgpu.bundle.min.mjs:2603 Uncaught Error: Can't create a session. Failed to allocate a buffer of 
size 2079238052.
    at jt (ort.webgpu.bundle.min.mjs:2603:25061)
    at Pr (ort.webgpu.bundle.min.mjs:2603:25240)
    at Kl (ort.webgpu.bundle.min.mjs:2603:34605)
    at mn.loadModel (ort.webgpu.bundle.min.mjs:2603:36389)
    at fn.createInferenceSessionHandler (ort.webgpu.bundle.min.mjs:2603:38145)
    at e.create (ort.webgpu.bundle.min.mjs:6:19471)
    at async createInferenceSession (onnx.js:163:1)
    at async models.js:301:1
    at async Promise.all (:5173/index 0)
    at async constructSessions (models.js:298:1)
```

I believe that 2079238052 bytes (approximately 1.94 GB) is less than 2 GB, so it shouldn't be causing this issue. Additionally, I noticed that the file `preprocessor_config.json` is being downloaded or loaded twice.

### Reproduction

```javascript
import { AutoProcessor, MultiModalityCausalLM } from "@huggingface/transformers";

const model_id = "onnx-community/Janus-1.3B-ONNX";
const processor = await AutoProcessor.from_pretrained(model_id);
const model = await MultiModalityCausalLM.from_pretrained(model_id);
```

**Comment by xenova** [comment]
Can you try using WebGPU? Also, I recommend the following dtypes, depending on whether fp16 is supported or not.

```js
const model_id = "onnx-community/Janus-1.3B-ONNX";
const fp16_supported = true; // do feature check
const model = await MultiModalityCausalLM.from_pretrained(model_id, {
      dtype: fp16_supported
        ? {
            prepare_inputs_embeds: "q4",
            language_model: "q4f16",
            lm_head: "fp16",
            gen_head: "fp16",
            gen_img_embeds: "fp16",
            image_decode: "fp32",
          }
        : {
            prepare_inputs_embeds: "fp32",
            language_model: "q4",
            lm_head: "fp32",
            gen_head: "fp32",
            gen_img_embeds: "fp32",
            image_decode: "fp32",
          },
      device: {
        prepare_inputs_embeds: "wasm", // TODO use "webgpu" when bug is fixed
        language_model: "webgpu",
        lm_head: "webgpu",
        gen_head: "webgpu",
        gen_img_embeds: "webgpu",
        image_decode: "webgpu",
      },
    })
```

**Comment by finalstack** [comment]
It's working now, thanks, @xenova! Much appreciated.
I will wait for the bug to be fixed.

**Comment by xenova** [comment]
Do you have an example for how to do this in the python library? My understanding is that the model generates exactly 576 tokens, so unless the image decoder can produce higher quality images, it can currently only generate 384x384 images.

**Comment by finalstack** [comment]
My bad, you're right—it's 384x384 after checking their docs. But what about `guidance` and `parallel_size`?

**Comment by xenova** [comment]
You should be able to pass `guidance_scale: 4` to the `generate_images` function. Batched generation technically works, but needs a bit more experimentation.

**Comment by zlelik** [comment]
Hi,
I found this combination does not work on NVIDIA RTX 4070 with 8GB VRAM.


```javascript

{
  prepare_inputs_embeds: "fp32",
  language_model: "q4",
  lm_head: "fp32",
  gen_head: "fp32",
  gen_img_embeds: "fp32",
  image_decode: "fp32",
}
``` 

with the same error
Can't create a session. failed to allocate a buffer of size 2079238052.

Does this model work with fp32 at all in the browser with WebGPU? All fp32 parameters like this do not work as well with different error
```javascript
{
  "prepare_inputs_embeds":"fp32",
  "language_model":"fp32",
  "lm_head":"fp32",
  "gen_head":"fp32",
  "gen_img_embeds":"fp32",
  "image_decode":"fp32"
}
```

RangeError: Array buffer allocation failed.

**Comment by xenova** [comment]
Indeed, the language model for example needs to be run at a lower quantization: fp32 is simply too large for a single file (which is currently a single ~5GB file). The q4f16 variant is ~700MB.

<img width="505" height="394" alt="Image" src="https://github.com/user-attachments/assets/98cb8e24-b3d2-474c-871e-a49bf89e5a02" />

**Comment by zlelik** [comment]
Thank you for your reply. What would be the best practical combination (which gives the best quality answers) for high-end PC with RTX 4070 to run in Chrome Browser? This one below with q4 for the language model does not work (error is: Can't create a session. failed to allocate a buffer of size 2079238052.):
```javascript
{
  prepare_inputs_embeds: "fp32",
  language_model: "q4",
  lm_head: "fp32",
  gen_head: "fp32",
  gen_img_embeds: "fp32",
  image_decode: "fp32",
}
```

**Comment by xenova** [comment]
I found this configuration when testing originally: https://huggingface.co/spaces/webml-community/Janus-1.3B-WebGPU/blob/main/src/worker.js#L47-L74, so probably those still :)
