### ISSUE TITLE
Trying to use custom finetuned Whisper Model with 

### ISSUE THREAD

**Issue by vijaim** [huggingface/transformers.js#1118]
### Question

@xenova I am trying to use our own Whisper fine tuned model https://huggingface.co/medxcribe/whisper-base.en with

https://huggingface.co/spaces/Xenova/whisper-web. I have uploaded into a seperate repo for reference https://huggingface.co/medxcribe/whisper-base-onnx.en.

We have converted the fine tuned medxcribe/whisper-base.en using this command. 

`pip install onnx==1.17.0
pip install onnxruntime==1.20.1
pip install transformers==4.35.2
optimum-cli export onnx --model medxcribe/whisper-base.en whisper_onnx --task automatic-speech-recognition-with-past --opset 14`

But unfortunately while load the Whisper-web, we are stuck with this below error 

Can't create a session"
    at t.createSessionFinalize (http://localhost:4173/assets/worker-1c2c88a7.js:1789:105945)
    at t.createSession (http://localhost:4173/assets/worker-1c2c88a7.js:1789:106543)
    at t.createSession (http://localhost:4173/assets/worker-1c2c88a7.js:1789:98867)
    at t.OnnxruntimeWebAssemblySessionHandler.loadModel (http://localhost:4173/assets/worker-1c2c88a7.js:1789:101717)
    at Object.createSessionHandler (http://localhost:4173/assets/worker-1c2c88a7.js:9:115048)
    at dn.create (http://localhost:4173/assets/worker-1c2c88a7.js:1:14653)
    at async constructSession (http://localhost:4173/assets/worker-1c2c88a7.js:1810:22248)
    at async Promise.all (index 2)
    at async WhisperForConditionalGeneration.from_pretrained (http://localhost:4173/assets/worker-1c2c88a7.js:1810:29662)
    at async AutoModelForSpeechSeq2Seq.from_pretrained (http://localhost:4173/assets/worker-1c2c88a7.js:1810:77285)

Any suggestions? On a high level there is a problem with the generated Onnx files.

**Comment by xenova** [comment]
This should be fixed by the latest optimum and transformers.js versions 🙏
