### ISSUE TITLE
Can't run webgpu-video-background-removal

### ISSUE THREAD

**Issue by chmjkb** [huggingface/transformers.js#1119]
### System Info

- Apple Macbook M1 Pro
- Browser: Arc 131.0.6778.205
- macOS Sequoia 15.1
- transformers.js: `2.17.2`

### Environment/Platform

- [X] Website/web-app
- [ ] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

I tried to run the webgpu video background removal example and I've encountered two issues:
```
Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at getModelJSON (@xenova_transformers.js?v=1e7f008e:14370:15)
    at async loadConfig (@xenova_transformers.js?v=1e7f008e:18834:14)
    at async PretrainedConfig.from_pretrained (@xenova_transformers.js?v=1e7f008e:18864:26)
    at async AutoModel.from_pretrained (@xenova_transformers.js?v=1e7f008e:21908:14)
    at async main.js:33:13
```
Which i managed to fix by setting `env.allowLocalModels` to `false`. However, then i encountered another error:
```
Uncaught Error: no available backend found. ERR: [wasm] TypeError: Cannot read properties of undefined (reading 'buffer')
    at resolveBackend (@xenova_transformers.js?v=1e7f008e:166:13)
    at async _InferenceSession.create (@xenova_transformers.js?v=1e7f008e:764:25)
    at async constructSession (@xenova_transformers.js?v=1e7f008e:19513:12)
    at async Promise.all (:5173/index 1)
    at async PreTrainedModel.from_pretrained (@xenova_transformers.js?v=1e7f008e:19900:14)
    at async AutoModel.from_pretrained (@xenova_transformers.js?v=1e7f008e:21924:14)
    at async main.js:33:13
```
Which is surprising, since i expected it to run on WebGPU instead of WASM.
I tried different versions of transformers.js but couldn't fix it though.
Thank you for creating this awesome library! :D 

### Reproduction

1. go into `webgpu-video-background-removal` dir
2. run `yarn && yarn dev`

**Comment by xenova** [comment]
Upgrading to `@huggingface/transformers` will fix this as since v3, we do not check local files first.
