### ISSUE TITLE
Support nomic-ai/nomic-embed-vision-v1.5

### ISSUE THREAD

**Issue by markthethomas** [huggingface/transformers.js#848]
### Model description

hey there! Was looking to use nomic-ai/nomic-embed-vision-v1.5 since I'm using the text version so I could support image / text queries using the same semantic space, but getting this error when I tried:

```Error: Failed to load model with error: /Users/runner/work/1/s/onnxruntime/core/graph/model.cc:146 onnxruntime::Model::Model(onnx::ModelProto &&, const onnxruntime::PathString &, const onnxruntime::IOnnxRuntimeOpSchemaRegistryList *, const logging::Logger &, const onnxruntime::ModelOptions &) Unsupported model IR version: 10, max supported IR version: 8

    at OnnxruntimeSessionHandler (/Users/....redacted..../node_modules/onnxruntime-node/lib/backend.ts:16:30)
    at <anonymous> (/Users/....redacted....node_modules/onnxruntime-node/lib/backend.ts:61:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)```

### Prerequisites

- [X] The model is supported in Transformers (i.e., listed [here](https://huggingface.co/docs/transformers/index#supported-models-and-frameworks))
- [X] The model can be exported to ONNX with Optimum (i.e., listed [here](https://huggingface.co/docs/optimum/main/en/exporters/onnx/overview))

### Additional information

_No response_

### Your contribution

I took a swing at re-converting to onnx using the provided script, but ran into some errors. It seems like there's already an `onnx` directory in the model files area, too, so that may be unnecessary

**Comment by markthethomas** [comment]
btw, this is the code I am running:

```javascript
    const { pipeline } = await import("@xenova/transformers");
    console.time("embedImage");
    const extractor = await pipeline(
        "image-feature-extraction",
        "nomic-ai/nomic-embed-vision-v1.5",
        { quantized: true}
    );
    const embeddings = await extractor(path);
    console.dir(embeddings);
    console.timeEnd("embedImage");
    return embeddings.tolist();
```

**Comment by mjp0** [comment]
I was just trying to run this as well but I'm getting "Can't create a session" error on both non-quantized and quantized. Same code. Tried on node 22.5.1 and bun 1.1.29.

`nomic-ai/nomic-embed-text-v1.5` works perfectly with feature-extraction pipeline.

**Comment by xenova** [comment]
ONNX weights were added for the model after this issue was opened, so it should work correctly now :) https://huggingface.co/nomic-ai/nomic-embed-vision-v1.5
