### ISSUE TITLE
[Feature request] Add Support for vicuna-13b-delta-v1.1

### ISSUE THREAD

**Issue by DK013** [huggingface/transformers.js#96]
**support for [vicuna-13b-delta-v1.1](https://huggingface.co/lmsys/vicuna-13b-delta-v1.1)
*NOTE: It's not listed in transformers supported models list but it does work with transformers*

**Reason for request**
With the upcoming WebGPU support in [ONNXRuntime](https://github.com/microsoft/onnxruntime) I believe it'll be really helpful to have an LLm support for browser based applications and this repo is the best solution we got so far.

**Additional context**
I've been working on an AI assistant made in electron and cordova for desktop and mobile platforms respectively. I'm already using TransformerJS with whisper for speech-to-text. I intend to switch to WebGPU with JSEP as soon it's available, so I can leverage the GPU compute capabilities to run larger models. I'm trying to build the project with as much opensource resources as possible and having an LLM support would be real nice instead of using openai apis. This keeps the project cost free for users and user's data-privacy is another benifit. I'm really looking forward to see if this is gonna be possible. I'm willing to contribute as much as I can being a complete novice to the ML community.

Thanks in advance

**Comment by xenova** [comment]
> I believe it'll be really helpful to have an LLm support for browser based applications and this repo is the best solution we got so far.

Agreed! WebGPU for onnxruntime-web is almost here (see https://github.com/microsoft/onnxruntime/pull/14579), and Transformers.js will support it when ready! There will be a massive announcement when it does drop! As for now, it is just a matter of waiting 😅 ...

**Comment by DK013** [comment]
> Agreed! WebGPU for onnxruntime-web is almost here (see [microsoft/onnxruntime#14579](https://github.com/microsoft/onnxruntime/pull/14579)), and Transformers.js will support it when ready! There will be a massive announcement when it does drop! As for now, it is just a matter of waiting 😅 ...

It's here !! They just merged the [js/web] WebGPU backend via JSEP [#14579](microsoft/onnxruntime#14579) few hours ago into the main brunch. No official release yet. Looks like @fs-eire openned another pull request for code cleanup and some small fixes. But we can build from the main brunch and start coding 😄

**Comment by fs-eire** [comment]
it takes some time and effort from enabling building from source, to including in the NPM package, to release as experimental feature, and then to final release.

I will keep working on stability, performance and coverage of the webgpu backend operator implementation in ort-web. this is going to be long-term work. Please feel free to "@" me or submit github issues to onnxruntime for feedback.

**Comment by xenova** [comment]
@fs-eire I have been following the build instructions from [here](https://onnxruntime.ai/docs/build/web.html), and I think I've sorted out most issues regarding dependencies, versions, etc. 

However, when running in the browser, I get the error `JS execution provider is not supported in this build`. Understandably, the docs have not yet properly been updated, so, would it be possible for you to provide steps to build from source, including what build arguments I should use? Thanks!

**Comment by DK013** [comment]
I've been looking at the updated files and under `<ORT_ROOT>/tools/ci_build/build.py` I can see there's arguments for `use_jsep` but it works within `build_wasm` from wha i can tell checking the yml conffigs for ci.
So I guess the build command will look something like this: `./build.bat --build_wasm --enable_wasm_simd --use_jsep --target onnxruntime_webassembly`
@xenova  Give it a try

**Comment by DK013** [comment]
Same story on my end. I checked your issue thread on the ort repo. Exact same errors on my end, except one. with `bert-base-cased_web` model and `webgpu` it gives me this error:
```
caught (in promise) TypeError: c.Da is not a function
    at 817149 (ort-wasm.js:20:91)
    at Ga (ort-wasm.js:28:361)
    at ort-wasm.wasm:0xcec891
    at ort-wasm.wasm:0x22535
    at ort-wasm.wasm:0x5093e3
    at ort-wasm.wasm:0x17906e
    at ort-wasm.wasm:0x76559e
    at ort-wasm.wasm:0xa36b99
    at Pa.b.<computed> (ort-wasm.js:38:150)
    at c._OrtCreateSession (ort-wasm.js:52:32)
```

**Comment by fs-eire** [comment]
@DK013 please use the workaround as described in https://github.com/microsoft/onnxruntime/issues/15719#issuecomment-1526216605 . I am working on a solution to fix the issue.

**Comment by DK013** [comment]
> @DK013 please use the workaround as described in [microsoft/onnxruntime#15719 (comment)](https://github.com/microsoft/onnxruntime/issues/15719#issuecomment-1526216605) . I am working on a solution to fix the issue.

@fs-eire I did. For `bert-base-cased_web` the wasm worked, webgpu didn't, even with your workaround. This was the error: 

> ```
> caught (in promise) TypeError: c.Da is not a function
>     at 817149 (ort-wasm.js:20:91)
>     at Ga (ort-wasm.js:28:361)
>     at ort-wasm.wasm:0xcec891
>     at ort-wasm.wasm:0x22535
>     at ort-wasm.wasm:0x5093e3
>     at ort-wasm.wasm:0x17906e
>     at ort-wasm.wasm:0x76559e
>     at ort-wasm.wasm:0xa36b99
>     at Pa.b.<computed> (ort-wasm.js:38:150)
>     at c._OrtCreateSession (ort-wasm.js:52:32)
> ```

**Comment by DK013** [comment]
@xenova As I can see fs-eire is working on the issues we've encountered before, and I'm running behind schedule on my own project, I'm implementing transformers.js with cpu for now in my code. Mainly I need whisper (a little more than the base model hopefully) to work right now and a suitable LLM model later on. So I'm gonna go ahead and complete the basic codes for testing right now, and wait for once you guys are done with polishing webgpu.
If you need any input from me, just let me know. 😉

**Comment by fs-eire** [comment]
@DK013 The PR mentioned above is merged, and another bugfix is in PR: https://github.com/microsoft/onnxruntime/pull/15819.

**Comment by matthoffner** [comment]
Catching up on this issue, does this mean there is conversational model support with the onnxruntime PRs? The README shows it as not supported yet. Thanks for any clarification!

**Comment by xenova** [comment]
> does this mean there is conversational model support with the onnxruntime PRs?

The [vicuna-13b-delta-v1.1](https://huggingface.co/lmsys/vicuna-13b-delta-v1.1) is categorized as a text-generation model (not a [conversational model](https://huggingface.co/models?pipeline_tag=conversational)), which is supported by Transformers.js. The distinction (which mainly lies in how they are used) is subtle, as both can be used for "conversations". For more information, see:
- https://huggingface.co/tasks/text-generation
- https://huggingface.co/tasks/conversational

**Comment by DK013** [comment]
@xenova heyo, I've been a bit busy with my own projects and running the business and all. what's the status of webgpu? How are your tests going?

**Comment by xenova** [comment]
> [@xenova](https://github.com/xenova) heyo, I've been a bit busy with my own projects and running the business and all. what's the status of webgpu? How are your tests going?

WebGPU support is stable -- especially in Transformers.js [v4](https://github.com/huggingface/transformers.js/pull/1382) (new) which adds many missing ops.
